INSERT INTO CLIENT(CLIENTID,CLIENTNAME,CLIENTCOMPANY,CLIENTPHONE,CLIENTADDRESS) VALUES
(NULL, 'John', 'Big Company', '111-111-1111', '103 queen street');

INSERT INTO EMPLOYEE(EMPLOYEEID,EMPNAME,EMPEMAIL,EMPROLE,EMPPHONE) VALUES
(NULL, 'Eric Cartman', 'cartman@gmail.com', 'worker', '222-222-2222');

INSERT INTO SCHEDULE(SCHEDULEID,SCHDAY,SCHMONTH,SCHYEAR,SCHSTARTTIME,SCHENDTIME,EMPLOYEEID,PROJECTID) VALUES
(NULL, '01', '05', '2021', '0800','1600', (SELECT EMPLOYEEID FROM EMPLOYEE WHERE EMPNAME = 'Eric Cartman'), (SELECT PROJECTID FROM PROJECT WHERE PROJLOCATION = 'man') );

INSERT INTO PROJECT(PROJECTID,PROJLOCATION,PROJESTCOMPLETEDATE,PROJESTCOMPLETECOST,PROJSTARTDATE,PROJENDDATE,CLIENTID) VALUES
(NULL, 'man', '11-11-22', '.99', '11-11-21', '10-10-22', (SELECT CLIENTID FROM CLIENT WHERE CLIENTNAME = 'John'));

